name: BetterSiege
version: 1.0
main: bettersiege.BetterSiege
description: A custom siege plugin for CI.
commands:
  sHelp:
    description: Provides general help for the plugin.
permissions:
  BetterSiege.*:
    default: false
  BetterSiege.buildCatapult:
    default: false
  BetterSiege.Catapult:
    default: false
  BetterSiege.Wall:
    default: false